version: '3.1'
services:
  app:
    working_dir: '/app'
    env_file: .env
    container_name: app_${APP_NAME}
    image: node:12
    ports:
      - '3333:3333'
    command: yarn
    command: yarn typeorm migration:run
    command: yarn dev:server
    volumes:
      - .:/app
    networks:
      - 'network_${APP_NAME}'
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    container_name: postgres_${APP_NAME}
    image: postgres
    environment:
       POSTGRES_DB: ${APP_NAME}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - .postgres:/var/lib/postgres/data
    networks:
      - 'network_${APP_NAME}'
    ports:
      - '5432:5432'

  mongo:
    container_name: mongo_${APP_NAME}
    image: mongo
    ports:
      - '27017:27017'
    volumes:
    - .mongo:/var/lib/mongo/data
    networks:
      - 'network_${APP_NAME}'

  redis:
    container_name: redis_${APP_NAME}
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - .redis:/var/lib/mongo/redis
    networks:
      - 'network_${APP_NAME}'

networks: 
  network_${APP_NAME}:
    driver: bridge

