version: '3.1'
services:
  app:
    working_dir: '/app'
    env_file: .env
    container_name: app_gobarber
    image: node:12
    ports:
      - '3333:3333'
    command: yarn
    command: yarn typeorm migration:run
    command: yarn dev:server
    volumes:
      - .:/app
    networks:
      - 'network_gobarber'
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    container_name: postgres_gobarber
    image: postgres
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - .postgres:/var/lib/postgres/data
    networks:
      - 'network_gobarber'
    ports:
      - '5432:5432'

  mongo:
    container_name: mongo_gobarber
    image: mongo
    ports:
      - '27017:27017'
    volumes:
    - .mongo:/var/lib/mongo/data
    networks:
      - 'network_gobarber'

  redis:
    container_name: redis_gobarber
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - .redis:/var/lib/mongo/redis
    networks:
      - 'network_gobarber'

networks: 
  network_gobarber:
    driver: bridge

